// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-gU5etpSNR9zBlSExXaPTCr6lcB2MjU4',
    appId: '1:321649419036:web:58eb8f069a7f6b0a2fd0d9',
    messagingSenderId: '321649419036',
    projectId: 'parcours-8eda0',
    authDomain: 'parcours-8eda0.firebaseapp.com',
    storageBucket: 'parcours-8eda0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqsZ4IOGkrEaR-JIOQgegSHUreSHwYCEM',
    appId: '1:321649419036:android:2750fd61d3f2f3352fd0d9',
    messagingSenderId: '321649419036',
    projectId: 'parcours-8eda0',
    storageBucket: 'parcours-8eda0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnruIfCXM3YMGLt6RTu_8IQcsBqPJf8_s',
    appId: '1:321649419036:ios:9f566f628d27f2352fd0d9',
    messagingSenderId: '321649419036',
    projectId: 'parcours-8eda0',
    storageBucket: 'parcours-8eda0.appspot.com',
    androidClientId: '321649419036-v6attn5u9tpinvbl9piilobn2utcd3q6.apps.googleusercontent.com',
    iosClientId: '321649419036-3mpha2ctnfo7sfrhfr5427032t8lr0cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnruIfCXM3YMGLt6RTu_8IQcsBqPJf8_s',
    appId: '1:321649419036:ios:9f566f628d27f2352fd0d9',
    messagingSenderId: '321649419036',
    projectId: 'parcours-8eda0',
    storageBucket: 'parcours-8eda0.appspot.com',
    androidClientId: '321649419036-v6attn5u9tpinvbl9piilobn2utcd3q6.apps.googleusercontent.com',
    iosClientId: '321649419036-3mpha2ctnfo7sfrhfr5427032t8lr0cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-gU5etpSNR9zBlSExXaPTCr6lcB2MjU4',
    appId: '1:321649419036:web:fc5b73ebffae76872fd0d9',
    messagingSenderId: '321649419036',
    projectId: 'parcours-8eda0',
    authDomain: 'parcours-8eda0.firebaseapp.com',
    storageBucket: 'parcours-8eda0.appspot.com',
  );
}
